import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
const { useState, useEffect } = require("react");
import getBlockchain from "../ethereum.js";
import axios from "axios";

export const Home = () => {
  const [tokenInfo, setTokenInfo] = useState(undefined);
  const [images, setImages] = useState([]);

  useEffect(() => {
    const init = async () => {
      const { nft } = await getBlockchain();
      const balance = await nft.balanceOf(
        nft.provider.provider.selectedAddress
      );

      console.log(`balance: ${balance}`);

      for (let i = 0; i < 2; i++) {
        // let tokenURI = await nft.tokenURI(i);
        // const data = await axios.get(tokenURI);
        // const picture = await data.data.properties.image.description;
        // setImages((images) => [...images, picture]);
      }
    };
    init();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Home;
